[gcp_service_account]
type = "service_account"
project_id = "sellout-automator"
private_key_id = "9942011571fb89519d62ed8ecf926092500290af"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCp46xiUHpMKHlI
uhRTUBAYTIdNKb91LjiNwBtxZef42tRTE/WSFxG8qoRojwFvdUpGXVdJKhK1pB8v
dc+fbrLDp8FmfQG0xzRxKvtVrCGMcSeQmn9zbBuScvqlvzQ6mdK/OAD5O/3f7Fgr
332rTdLcW9e366qWm3rG7rNBg2rtG8xmvbGCAZMTngNkXJIaw4BLO9ezid4/HmMo
8d48qDGThzaCxprOSgjMhyQ4YO/QBD19mp8Y3M17sL0ypgV3my4yz21wlQEvPCwd
nfUqmAwviT4wwIVAbV03Y13YXfBZmv+uco4x6YMU367qrSUCTBldZUTF/oguTeR6
FXIFTMUjAgMBAAECggEAEhfY7xY1FXv7Vr8tP6Y3i0RIkJ478WXnyKjyA0S1d4UO
tykEA/gIVTiFJiw8xzsNmwAr4J3mJN7YIhIrojDZlwl8XnGScfID6B2KFkNhG0zz
HW0RhSBkBgJ60UDTdijrD0m5SNHr0CJNTaGIB8DKY9o1gjVLaK4hsvgPB+YlcspR
ABkhed7G3np2z8dmQkoNekkJriVQJc301CSHOr4LEKsI5Z2oETfvZEQ0PAQaQZEF
Wkjp+ksXToTTTwduzOdTOXAKDTJnzAIChj6uDLUmGZ79xclzlsQ03rCPhMqjB21W
ZyFkkBSQWWyMtPEVRNXYICiz2784+YUVEMH1nHtVYQKBgQDYASQ5NI1qRTGhRAOO
V60tK6fyWsaBgmaUGpHLj2aL1mL1QwCkn18SCsobcOdv+GOCRLEAXH//cnPidMtl
bew4EQ3igqr1KOhsfpsjuWsGl+8O+GvZiGOcUqUNxtcXCXI8H85N4bm+kiRjpsi2
nZ+ISeuX9Oa4AoCHmaQx6etQEwKBgQDJWJ92zHj2KCyjekMatZ1uMQedu3z9rQD4
ab0+7MjvX9RGs9a5DtMTjcfS3eJ8d8QUYzFHeKcIAGfcDh1o5gQAMLkjQauC4gLE
vAcsCOGCSyM5Lh0jho4HD/JNYMg6UvIPD1oi5HJPZfrT4oUfNWE7SUODZzBDXJHQ
H/F5rNj4sQKBgQCYb6XKoSWze4Vc04zW5VUXbZmmVR2FxCr0FhQR3e92fCN2BoTr
qHUFXIvo9bK+uEIxapynLqA9+92AUQBBYmOz5YUw9xoCzY3JE0gU3AOFsa9Jl1M1
PyVc6o4EvPCKF2aAu8lx+PyGWshHcypuhapSGiijIne4IDvodisD9prT9QKBgQCq
XATYxJsYU9epHnqGr+IbaPqzt/5CuU3X4cfQ5RICj8eRZvqoK+XmZpELVtgaTk+m
nGMGwQw61fUKmRrDNdNuwcr0DM1seYS0Jw++b2k3EBImgGEBPQkQ6qouVFQ2HRZY
LborSbV6fqPjAYd3Z3f0bMHl/bo1VK6/NTfgpqISkQKBgQDRPj6a8LmKjJxDTdr0
5SslH5AgNZq0tgWMdHymSVtufnfi+D9Hx4l50z/++seF1H8Zt5vVSRrhri14XGg5
YnzxvHewa+Bxtty4HbWOo43A5e9gGQWOP8d2Tqt6svjrPwQOQ6/YXytVTkd6onzH
Db4iKp/xd8Gn/PqGOIfy/KZcSQ==
-----END PRIVATE KEY-----'''
client_email = "sellout-automator@sellout-automator.iam.gserviceaccount.com"
client_id = "107394028145897384412"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sellout-automator@sellout-automator.iam.gserviceaccount.com"
[openai]
api_key = "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"
